twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
      panier: "@App\\Cart\\Panier"

when@test:
    twig:
        strict_variables: true
