version: '3'
services:
  web:
    build: ./
    ports:
      - "92:80"
    depends_on:
      - db
    expose:
      - 9010
    volumes:
      - ./:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/ini/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
      # - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      # - ./proxy/certs:/etc/nginx/cerst
    networks:
      - aksamAssuranceV6_network

  db:
    image: mysql
    ports:
      - "3321:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aksamAssuranceV6_db
      MYSQL_USER: badrman
      MYSQL_PASSWORD: 123456789
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - aksamAssuranceV6_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8281:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - aksamAssuranceV6_network

networks:
  aksamAssuranceV6_network:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
